name: run-script
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to vps
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 27.112.79.120
        password: Tanpapass556_
        script: echo "hello world"
