

    name: run-script
    on: push

    jobs:
    run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: script
    - run: |
    "${GITHUB_WORKSPACE}/.github/script.sh";
    "${{ format('{0}/.github/script.sh', github.workspace) }}";
    shell: bash
    with:
    password: ${{ secrets.ACCESS_TOKEN }}
