name: run-script
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to vps
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        password: ${{ secrets.PASSWORD }}
        script: 'cd /home/inhospital21 && ./autoDeploy.sh'
